---
- name: sksk
  hosts: all
  become: yes

  tasks:
  - name: httpdinstall hahahahaha
    yum:
      name: httpd
      state: present

  - name: get_grl
    get_url: url=www.sk.com dest=/var/www/html/index.html
    



  - name: start!!!
      service:
        name: httpd
        state: started
