---
- name: sksk
  hosts: all
  become: yes

  tasks:
  - name: httpdinstall hahahahaha
    yum:
      name: httpd
      state: present

  - name: start!!!
      service:
        name: httpd
        state: started
